### ISSUE TITLE
AuthN & AuthZ ?

### ISSUE THREAD

**Issue by coltnz** [lvh/caesium#39]
Hi first thanks for Caesium, we're using it at http://smxemail.com in email security products.

Any thoughts on Caesium for authn and authz? Can't see much out there.  I guess the low hanging fruit is as a buddy backend - though I have some reservations on buddy. 

Something based on Clara Rules would be cool.

cheers
Colin

**Comment by lvh** [comment]
You mean as in browser cookies or internal sessions, or something else? I definitely have lots of opinions there :)

**Comment by coltnz** [comment]
Oops missed my notification on this.

In short I've got a new Clojure webapp to build and I'm looking for a session token and a rules system based on libsodium. Was hoping someone had done something or planned something based on caesium. I'm comfortable building the rules but I'd rather trust the token to somebody else or at least an approved protocol.

Hadn't seen PAST I'll have a look.

**Comment by lvh** [comment]
Gotcha. Either caesium or PAST will be fine. The latacora free advice policy stands; FWIW; while there might be a decent reason to do this, we'd generally recommend against storing that information in a cookie.

That said, nobody''s done rule based eval with caesium session tokens to my knowledge so I'll close this one out :)
