### ISSUE TITLE
Any help needed?

### ISSUE THREAD

**Issue by eploko** [lvh/caesium#68]
The current SNAPSHOT version works fine, but I'm a tad worried some of the old tests fail, the build doesn't pass on CI, and the dependencies are marked as not up-to-date.

I'd like to spend some time to polish the things out and would like to know what'd be a proper direction of tackling this. @lvh, what are your thoughts on all of this?

**Comment by lvh** [comment]
Sweet! I would definitely appreciate the help and I was definitely disappointed that CI broke at some point when I wasn't looking.

I think a great place to start would be to fix CI maybe by moving to GitHub Actions? I have no idea when or why Travis CI started failing. You could also debug that I guess? But it might be easier to just get GA working.

I can absolutely commit to time for code reviews and guidance and release management. Also you can just tag me on stuff you want eyeballs on.

**Comment by eploko** [comment]
Roger. I'll look in what can be done to stabilize the tests the first thing. Will close this issue and will open others as I progress.
