### ISSUE TITLE
Unable to decrypt strings encrypted with `secretbox-nmr` across JVM restarts on MacOS

### ISSUE THREAD

**Issue by mikeclarke** [lvh/caesium#73]
Thanks for the great library.

We're hitting an issue on MacOS where a string that is encrypted with `caesium.magicnonce.secretbox/secretbox-nmr` without a nonce (just a key and string as arguments) produces a byte array that cannot be decrypted after a JVM restart.

```
(require '[byte-streams :as bs])
(require '[caesium.magicnonce.secretbox :refer [secretbox-nmr] :as sb])
(org.apache.commons.codec.binary.Hex/encodeHexString (-> "secret" bs/to-byte-array (secretbox-nmr "asdf")))
<long hex string is printed>
(String. (-> (org.apache.commons.codec.binary.Hex/decodeHex (.toCharArray *1)) bs/to-byte-array (sb/open "asdf")))
"secret"
```
then following a JVM restart

```
(require '[byte-streams :as bs])
(require '[caesium.magicnonce.secretbox :refer [secretbox-nmr] :as sb])
(String. (-> (org.apache.commons.codec.binary.Hex/decodeHex (.toCharArray <long hex string>)) bs/to-byte-array (sb/open "asdf")))
Execution error at caesium.crypto.secretbox/secretbox-open-easy-to-buf! (secretbox.clj:50).
Ciphertext verification failed
```

libsodium is 1.0.18 on java 11, `commons-codec 1.6` and `caesium 0.10` but bumping the library versions didn't help here.

Are there any known issues with libsodium + caesium on MacOS? Is there something that needs to be initialized to make decryption work across reloads? Thanks!

**Comment by lvh** [comment]
Your key still needs to be a secretbox key, and `secret` won't cut it. secretbox is going to read 32 bytes starting from the start of that byte buffer., and all but 6 of those bytes (`s e c r e t`) are going to be whatever was in RAM at the time.

I think someone else has ran into this before, so perhaps the right answer is for the high level APIs to validate these invariants.

**Comment by mikeclarke** [comment]
Thanks @lvh - this feedback pointed me in the right direction. We're passing a decoded hex byte array (via http://commons.apache.org/proper/commons-codec/archives/1.9/apidocs/org/apache/commons/codec/binary/Hex.html#decodeHex(char[])) rather than a string as the secretbox key, and I believe the bug I encountered is the same issue you described - insufficient bytes in the buffer causing  junk in RAM to be read.

Is the 32 byte requirement constant across all environments? I'm assuming that's coming from libsodium.

Thanks for the quick response!

**Comment by lvh** [comment]
Yeah, that's definitely consistent, it's specified by secretbox in this case.
