### ISSUE TITLE
Using `caesium` on Apple Silicon (M1, `aarch64`)

### ISSUE THREAD

**Issue by dancmeyers** [lvh/caesium#85]
I'm trying to get `caesium` working on Apple Silicon, since our devs have all, up till now, used Macs, and Apple don't ship new Intel Macs any more.

On the working Intel system I've got AdoptOpenJDK 11 installed, with `libsodium`, both from Homebrew. No worries there. On the M1 Mac I have so far tried:

- AdoptOpenJDK 11 and `libsodium`, both compiled for `x86_64`, installed from Homebrew, run via Rosetta.
- Eclipse Temurin JDK 11 and `libsodium`, both compiled for `x86_64`, installed from Homebrew, run via Rosetta.
- Azul Zulu JDK 11 and `libsodium`, both compiled for `arm64`, installed from Homebrew.
- Eclipse Temurin JDK 17 and `libsodium`, both compiled for `arm64`, installed from Homebrew.

In the latter two cases I also tried creating symlinks from the `libsodium` install files (`/opt/homebrew/lib/libsodium.23.dylib`, `/opt/homebrew/lib/libsodium.dylib`, `/opt/homebrew/lib/libsodium.a` and `/opt/homebrew/lib/pkgconfig/libsodium.pc` to their equivalent locations under `/usr/local` where Homebrew creates them on the Intel machine).

In all cases I just got the error:
```
user=> (require '[caesium.binding :as cb])
Execution error (ClassNotFoundException) at caesium.binding/load-sodium (binding.clj:643).
unable to load native libsodium; is it installed?
```

This is using `caesium` v0.14.0. I notice in `master` you also print the exception that caused the library load to fail, so I tried that. I built my own version of `caesium`, ran it successfully on the Intel Mac, then tried it on the M1. The error it gave this time was:
```
user=> (require '[caesium.binding :as cb])
Execution error (MethodTooLargeException) at jdk.internal.org.objectweb.asm.MethodWriter/computeMethodInfoSize (MethodWriter.java:2118).
Method too large: jdk/proxy3/$Proxy3.<clinit> ()V
```

I don't understand enough about JNR FFI (or possibly something it's doing internally) to understand how I can get that error on the M1 but not on the Intel machine. Surely the same limits will apply to the JDK on both?

I tried following the calls through the JNR FFI code, and couldn't see what library paths it might be searching for the relevant files. Any of the `LD_xxxx` or `DYLD_xxxx` env vars are empty on both machines, and in both cases the directories listed under the JVM property `java.library.path` are either empty or nonexistent. I did notice that newer versions of JNR FFI (`2.2.3` and beyond) manually add the paths `/usr/local/lib`, `/usr/lib` and `/lib` (here: https://github.com/jnr/jnr-ffi/blob/7b733418ae7c34b26ce31c87e730810aaa20740e/src/main/java/jnr/ffi/LibraryLoader.java#L505-L510) if the system `isUnix` (which basically amounts to "is not Windows"), but rebuilding my local Caesium with a bumped version of JNR FFI to get that addition in made no difference, I still get the `MethodTooLargeException` error.

Any hints as to anything else I should be looking at?

**Comment by dancmeyers** [comment]
For anyone else coming along to this, here is what I have worked out so far:

- Macos on Apple Silicon _requires_ that any `arm64` binaries and libs are signed before it will allow them to run.
- Because of this, both the JDK and `libsodium` are signed when `arm64` versions are fetched from Homebrew, and yet for some reason Caesium still can't see/use `libsodium`. Is the platform security complaining about the way it links into the library using JNR FFI? Does that install libs which would need to be signed too?
- On Intel Macos, the `libsodium` libs from Homebrew are unsigned, but the JDK still is. As such, you need to explicitly unsign the JDK (`sudo codesign --remove-signature ${JAVA_HOME}/bin/java`) for Caesium to work. I had, admittedly, forgotten this from when I last installed on an Intel Mac.
- The codesigning requirement is only for `arm64` binaries/libs. `x86_64` binaries/libs, run via Rosetta, can still be unsigned on Apple Silicon Macos.
- If you use `arch -x86_64 ...` to run the Homebrew install script, it will install in `/usr/local` as in Intel Macs, instead of `/opt/homebrew` as is the default on Apple Silicon. The same `arch` command to run `brew install` using the `/usr/local` Homebrew will fetch and install the `x86_64` version of the package.
- Homebrew won't allow you to install `x86_64` packages to `/opt/homebrew`.

As such, I was able to get this working by running:
- `arch -x86_64 ./install.sh` with the `brew` install script, to install Homebrew to `/usr/local`.
- `arch -x86_64 /usr/local/Homebrew/bin/brew install temurin libsodium` to install the `x86_64` versions of both the JDK (signed) and `libsodium` (unsigned).
- `sudo codesign --remove-signature ${JAVA_HOME}/bin/java` to strip the signature from the Java binary.

I can then run a `lein repl`, load Caesium, perform the usual cryptography functions we were using it for etc, all through Rosetta on a JVM that is compiled for Intel Macos.

**Comment by dancmeyers** [comment]
Ideally this would work in native `arm64` Macos as well, but I'm just happy I've got it to work... No idea what would be necessary to make Caesium see and be able to use a signed `libsodium` via a signed `java`.

**Comment by lmtriet** [comment]
@dancmeyers 
I have followed your procedure to install brew, libsodium and temurin17 using arch x86-64 in /usr/local but I still get the MethodTooLargeException when trying to run Caesium binding_test.clj from IntelliJ.
Do you remember anything else you have done to get this to work ?

I might try to migrate from Caesium to LazySodium next week. They seems to solve the compatibility problem.

**Comment by lmtriet** [comment]
Follow up to my previous comment, the only test that doesn't work is binding-test.clj/library-not-installed-test. Other tests passed.

Thank you @dancmeyers for your post.

**Comment by arohner** [comment]
Bumping jnr-ffi to latest, `com.github.jnr/jnr-ffi {:mvn/version "2.2.12"}` worked for me on M1

**Comment by lvh** [comment]
FYI I just bumped jnr-ffi since there's a report this might help; thanks @arohner :)
